---

- name: update mariadb root password for all root accounts
  mysql_user:
    user: root
    host: '{{ item }}'
    password: '{{ mariadb_root_password }}'
    state: present
  with_items:
   - localhost

- name: copy the mariadb.cnf file
  template:
    src: my.cnf.j2
    dest: /etc/mysql/mariadb.cnf
    owner: root
    group: root
    mode: 0644
  notify: mariadb_restart

- name: copy the sub config files
  template:
    src: config.cnf.j2
    dest: '/etc/mysql/{{ item.location }}/{{ item.name }}.cnf'
    owner: root
    group: root
    mode: 0644
  with_items: '{{ mariadb_config_files }}'
  notify: mariadb_restart

- name: reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: ensure anonymous users are not in the database
  mysql_user:
    name: ''
    host: '{{ item }}'
    state: absent
  with_items:
   - localhost
   - '{{ ansible_hostname }}'

- name: Dont allow root login remotely
  mysql_user:
    name: root
    host: '{{ ansible_hostname }}'
    state: absent

- name: remove the test database
  mysql_db:
    name: test
    state: absent
